### PR TITLE
whitespace to get travisCI to run the tests

### PR DESCRIPTION
**Pull request by brummett**
TravisCI is failing a couple of test cases in database.t and template.t.  This branch is to explore why.

### CODE REVIEW

**Comment by nnutter** [comment]
Looks like the failures are intermittent.

**Comment by brummett** [comment]
Not intermittent.  The real fix is in #70.  The first commit on this branch was failing earlier.  I don't know why it's marked as succeeding now.

**Comment by nnutter** [comment]
Because I re-ran the job which spurred my intermittent comment.  The job claims to be testing the same commit each time: 332a7f74a0c8278d04ac234a494b117e3bd9dffe.

**Comment by brummett** [comment]
#66 and #67 are failing in the exact same way this first commit did, no matter how many times I re-run them.

**Comment by nnutter** [comment]
Travis CI lies.  It's grabbing the latest PR merge head.

**Comment by nnutter** [comment]
I filed a bug report, [#3387](https://github.com/travis-ci/travis-ci/issues/3387).

**Pull request closed without merging**
