### PR TITLE
Return 503 if the database server can't make the database

### LINKED ISSUE #60: full disk on server result in a "400 Bad Request" error
We filled up the disk on `apipe-test-db` and if you tried to create a new database it would error with "400 Bad Request",

```
$ test-db database create --based-on 23a5ccf --owner genome
Got error response 400: Bad Request at /usr/bin/test-db-database-create line 15
```

### PR DESCRIPTION
**Pull request by brummett**
This is intended to resolve #60, but it doesn't solve that particular problem.
It looks like the full-disk problem makes the CREATE DATABASE statement in
PostgresInstance::createdb_from_template() fail, which throws
Exception::CannotCreateDatabase.  Without parsing the test of the error
returned by the server, we can't deduce why it failed.

The test is kind if cheesy, relying on the one and only do() to be that
CREATE DATABASE statement.

We're now catching that exception and returning 503 instead of the default 400.

### CODE REVIEW

**Comment by nnutter** [comment]
I really don't know anything but 403 might be better for this general case of `CannotCreateDatabase`.

**Comment by brummett** [comment]
I don't know any more than you do.  I thought 4xx codes were supposed to be errors in the request from the client, and 5xx codes were errors that occurred on the server.  Since the client is making a valid request, 5xx seemed appropriate.  Maybe 507 would be a better fit for this condition: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_Server_Error

**Comment by nnutter** [comment]
I think REST APIs usually avoid the WebDAV "extensions" to HTTP codes.  Also, this isn't necessarily specific to the storage.  I don't know if we can assume that a CannotCreateDatabase means the service is unavailable (503).  However, it does seem like we do a lot of validation so that any other case I can think of that would cause CannotCreateDatabase would fail earlier as a bad request; so maybe 503 is alright.  We could always use 500 if we want something generic.

**Comment by brummett** [comment]
This branch now passes tests after merging in the fix from #70.

Returning 503 here seems like a reasonable balance between parsing the error text from CREATE DATABASE and returning a generic 500.

Do we agree that 503 is the right thing to do when we can't create the database?

**Comment by nnutter** [comment]
I'm still torn about which to use but I definitely think 503 is better than 400 so I think we should merge this. :+1:

**Pull request merged**
